serviceAccount:
  name: ${serviceaccount_name}
  annotations:
    eks.amazonaws.com/role-arn: "${iam_role_arn}"

resources:
  limits:
    cpu: 200m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 200Mi

# enableRebalanceMonitoring If true, cordon nodes when the rebalance recommendation notice is received. Only used in IMDS mode.
enableRebalanceMonitoring: true

awsRegion: ${cluster_region}
