clusterName: ${cluster_name}

serviceAccount:
  name: ${serviceaccount_name}
  annotations:
    eks.amazonaws.com/role-arn: "${iam_role_arn}"

resources:
  limits:
    cpu: 200m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 200Mi

enableCertManager: true

region: ${cluster_region}

vpcId: ${vpc_id}