---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-access
  namespace: ${namespace}
rules:
  - apiGroups: ["", "apps", "autoscaling", "batch", "extensions"]
    resources: ["*"]
    verbs: ["*"]
