---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-access
  namespace: ${namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin-access
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: ${group_name}
