# https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml
credentials:
  useSecret: false

configuration:
  backupStorageLocation:
    - provider: aws
      bucket: ${bucket}
  volumeSnapshotLocation:
    - provider: aws
      config:
        region: ${region}

serviceAccount:
  server:
    name: ${serviceaccount_name}
    annotations:
      eks.amazonaws.com/role-arn: ${role_arn}

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:${aws_container_version}
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

schedules:
  fullbackup:
    disabled: false
    schedule: ${schedule_cron}
    useOwnerReferencesInBackup: true
    template:
      ttl: 720h

snapshotsEnabled: false
