autoDiscovery:
  clusterName: ${cluster_name}
awsRegion: ${cluster_region}
rbac:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "${iam_role_arn}"
resources:
  requests:
    cpu: 50m
    memory: 128Mi
extraArgs:
  stderrthreshold: error
  skip-nodes-with-local-storage: false
  balance-similar-node-groups: true
  skip-nodes-with-system-pods: false
  scale-down-utilization-threshold: ${scale_down_cpu_threshold}
