prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi

prometheus:
  prometheusSpec:
    resources:
      requests:
        cpu: 800m
        memory: 1500Mi
    ## How long to retain metrics
    ##
    retention: 5w
    ## Maximum size of metrics
    ##
    retentionSize: "25GB"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "${storage_class_name}"
          resources:
            requests:
              storage: 50Gi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 3m
      memory: 16Mi

grafana:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 2m
      memory: 20Mi
