---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer-access
  namespace: ${namespace}
rules:
  - apiGroups: ["", "extensions", "apps", "batch"]
    resources:
      [
        "deployments",
        "replicasets",
        "pods",
        "pods/log",
        "configmaps",
        "events",
        "ingresses",
        "ingresses/status",
        "pods/portforward",
        "secrets",
        "cronjobs",
        "services",
      ]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["pods/exec", "pods/portforward"]
    verbs: ["create"]
